Repository cycloidio/cycloid-cli, pull requests merged in 2021-01, with the labels that each got.

#69 infrapolicy: new command
  Makefile
  README.md
  client/client/api_client_client.go
  client/client/organization_infrastructure_policies/create_infra_policy_parameters.go
  client/client/organization_infrastructure_policies/create_infra_policy_responses.go
  client/client/organization_infrastructure_policies/delete_infra_policy_parameters.go
  client/client/organization_infrastructure_policies/delete_infra_policy_responses.go
  client/client/organization_infrastructure_policies/get_infra_policies_parameters.go
  client/client/organization_infrastructure_policies/get_infra_policies_responses.go
  client/client/organization_infrastructure_policies/get_infra_policy_parameters.go
  client/client/organization_infrastructure_policies/get_infra_policy_responses.go
  client/client/organization_infrastructure_policies/organization_infrastructure_policies_client.go
  client/client/organization_infrastructure_policies/update_infra_policy_parameters.go
  client/client/organization_infrastructure_policies/update_infra_policy_responses.go
  client/client/organization_infrastructure_policies/validate_project_infra_policies_parameters.go
  client/client/organization_infrastructure_policies/validate_project_infra_policies_responses.go
  cmd/cycloid.go
  cmd/cycloid/infrapolicies/cmd.go
  cmd/cycloid/infrapolicies/common.go
  cmd/cycloid/infrapolicies/validate.go
  cmd/cycloid/middleware/infra-policies.go
  cmd/cycloid/middleware/middleware.go
  printer/table/printer.go
  printer/table/printer_test.go
Labels: enhancement

#61 cmd/stackforms: add `gen-doc` subcommand
  CHANGELOG.md
  README.md
  cmd/cycloid.go
  cmd/cycloid/creds/create.go
  cmd/cycloid/pipelines/diff.go
  cmd/cycloid/stacks/cmd.go
  cmd/cycloid/stacks/common.go
  cmd/cycloid/stacks/gendoc.go
  cmd/cycloid/stacks/gendoc_test.go
  cmd/cycloid/stacks/get.go
  cmd/cycloid/stacks/list.go
  cmd/cycloid/stacks/testdata/stacks/error.yml
  cmd/cycloid/stacks/testdata/stacks/success.md
  cmd/cycloid/stacks/testdata/stacks/success.yml
  cmd/cycloid/stacks/validate-form.go
  e2e/login_test.go
Labels: Status: In progress, enhancement

#77 cycloid/common: add --insecure flag
  CHANGELOG.md
  cmd/cycloid/common/helpers.go
  main.go
Labels: Status: Need review

#73 forms: convert models.FormsFile to fit JSON standards
  cmd/cycloid/middleware/stacks.go
  cmd/cycloid/middleware/utils.go
Labels: Status: Need review
